#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# MIZAN Version Bump Script
#
# Usage:
#   ./scripts/bump-version.sh patch    # 3.0.0 → 3.0.1
#   ./scripts/bump-version.sh minor    # 3.0.0 → 3.1.0
#   ./scripts/bump-version.sh major    # 3.0.0 → 4.0.0
#   ./scripts/bump-version.sh 3.2.0    # set exact version
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ───── Colors ─────
GOLD='\033[0;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "  ${GOLD}➜${NC} $1"; }
success() { echo -e "  ${GREEN}✓${NC} $1"; }
error()   { echo -e "  ${RED}✗${NC} $1"; exit 1; }

# ───── Read current version ─────
VERSION_FILE="$ROOT_DIR/VERSION"
if [ ! -f "$VERSION_FILE" ]; then
    error "VERSION file not found at $VERSION_FILE"
fi

CURRENT=$(cat "$VERSION_FILE" | tr -d '[:space:]')
echo -e "\n  ${BOLD}Current version:${NC} ${GOLD}$CURRENT${NC}"

# ───── Parse current version ─────
BASE_CURRENT=$(echo "$CURRENT" | sed 's/-.*//')
IFS='.' read -r MAJOR MINOR PATCH <<< "$BASE_CURRENT"

# ───── Calculate new version ─────
case "${1:-}" in
    patch)
        NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
        ;;
    minor)
        NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
        ;;
    major)
        NEW_VERSION="$((MAJOR + 1)).0.0"
        ;;
    beta)
        # Parse base version (strip any existing pre-release suffix)
        BASE_VER=$(echo "$CURRENT" | sed 's/-.*//')
        IFS='.' read -r BM BMI BP <<< "$BASE_VER"
        NEXT_MINOR="$BM.$((BMI + 1)).0"
        if echo "$CURRENT" | grep -q "beta"; then
            BETA_NUM=$(echo "$CURRENT" | grep -oP 'beta\.\K[0-9]+' || echo "0")
            NEW_VERSION="${NEXT_MINOR}-beta.$((BETA_NUM + 1))"
        else
            NEW_VERSION="${NEXT_MINOR}-beta.1"
        fi
        ;;
    rc)
        BASE_VER=$(echo "$CURRENT" | sed 's/-.*//')
        if echo "$CURRENT" | grep -q "rc"; then
            RC_NUM=$(echo "$CURRENT" | grep -oP 'rc\.\K[0-9]+' || echo "0")
            NEW_VERSION="${BASE_VER}-rc.$((RC_NUM + 1))"
        elif echo "$CURRENT" | grep -q "beta"; then
            BASE_VER=$(echo "$CURRENT" | sed 's/-.*//')
            NEW_VERSION="${BASE_VER}-rc.1"
        else
            NEW_VERSION="${CURRENT}-rc.1"
        fi
        ;;
    "")
        echo ""
        echo "Usage: $0 <patch|minor|major|beta|rc|X.Y.Z[-beta.N]>"
        echo ""
        echo "  patch   $CURRENT → $MAJOR.$MINOR.$((PATCH + 1))"
        echo "  minor   $CURRENT → $MAJOR.$((MINOR + 1)).0"
        echo "  major   $CURRENT → $((MAJOR + 1)).0.0"
        echo "  beta    $CURRENT → $MAJOR.$((MINOR + 1)).0-beta.1"
        echo "  rc      $CURRENT → X.Y.Z-rc.1"
        echo "  X.Y.Z   Set exact version"
        exit 0
        ;;
    *)
        # Validate semver format (with optional pre-release)
        if [[ ! "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)\.[0-9]+)?$ ]]; then
            error "Invalid version format: $1 (expected X.Y.Z or X.Y.Z-beta.N)"
        fi
        NEW_VERSION="$1"
        ;;
esac

echo -e "  ${BOLD}New version:${NC}     ${GREEN}$NEW_VERSION${NC}\n"

# ───── Update all version locations ─────

# 1. VERSION file (single source of truth)
echo "$NEW_VERSION" > "$VERSION_FILE"
success "VERSION"

# 2. backend/_version.py
cat > "$ROOT_DIR/backend/_version.py" << EOF
"""Single source of truth for MIZAN version — auto-generated by scripts/bump-version.sh"""

__version__ = "$NEW_VERSION"
EOF
success "backend/_version.py"

# 3. pyproject.toml
sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" "$ROOT_DIR/pyproject.toml"
success "pyproject.toml"

# 4. frontend/package.json
sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" "$ROOT_DIR/frontend/package.json"
success "frontend/package.json"

# 5. backend/cli.py — banner and version command
NEW_BASE=$(echo "$NEW_VERSION" | sed 's/-.*//')
IFS='.' read -r NM NMI NP <<< "$NEW_BASE"
SHORT_VER="$NM.$NMI"
sed -i "s/MIZAN v[0-9][0-9]*\.[0-9][0-9]*/MIZAN v$SHORT_VER/" "$ROOT_DIR/backend/cli.py"
sed -i "s/MIZAN v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/MIZAN v$NEW_VERSION/" "$ROOT_DIR/backend/cli.py"
success "backend/cli.py"

# 6. backend/api/main.py — FastAPI version and API responses
sed -i "s/\"version\": \"[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*[^\"]*\"/\"version\": \"$NEW_VERSION\"/g" "$ROOT_DIR/backend/api/main.py"
sed -i "s/version=\"[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*[^\"]*\"/version=\"$NEW_VERSION\"/" "$ROOT_DIR/backend/api/main.py"
success "backend/api/main.py"

# ───── Summary ─────
echo ""
echo -e "  ${GREEN}${BOLD}Version bumped: $CURRENT → $NEW_VERSION${NC}"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo -e "    ${GOLD}git add -A && git commit -m \"chore: bump version to $NEW_VERSION\"${NC}"
echo -e "    ${GOLD}git tag v$NEW_VERSION${NC}"
echo -e "    ${GOLD}git push origin main --tags${NC}"
echo ""
echo -e "  Or use: ${GOLD}./scripts/release.sh $NEW_VERSION${NC}"
echo ""
